### ISSUE TITLE
bless ring bugs

### ISSUE THREAD

**Issue by Kastik404** [Auviotre/Enigmatic-Addons#12]
After cleansing the ring of seven curses, I lost the ability to knock out evil essence from the wither and the heart of the abyss from the dragon. Also, the total game time does not accumulate as it was with the cursed ring. I can craft all cursed artifacts, but I can not use all cursed artifacts, for example, as in the attached screenshot.
![изображение](https://github.com/user-attachments/assets/f3412ec8-fad6-45ab-92d8-be2eb605bdf1)

**Comment by Kastik404** [comment]
Ok, I get it, Is it possible to ask for a function to turn on and off such a balance in the configs? I am working on a modpack that is based on the cursed ring, and this case ruins the game.

**Comment by Auviotre** [comment]
I see. Making a config is a bit difficult. I'll think of it.

**Comment by Auviotre** [comment]
Or you can just use the config to disable the bless stone?

**Comment by Kastik404** [comment]
It's certainly possible, but it's not fun.

**Comment by Auviotre** [comment]
OK, fine.
