### ISSUE TITLE
[1.20.1] server crash or kick when equip lost engine

### ISSUE THREAD

**Issue by Milan4ikdudewtf** [Auviotre/Enigmatic-Addons#2]
i dont tested another artifacts but i think its only spellstones issue
[latest.log](https://github.com/user-attachments/files/16802622/latest.log)

**Comment by qwek1** [comment]
[latest.log](https://github.com/user-attachments/files/16822522/latest.log)
[debug.log](https://github.com/user-attachments/files/16822523/debug.log)

Encountered the same issue, just providing the logs here.
